### ISSUE TITLE
Potential issue regarding unfreezing

### ISSUE THREAD

**Issue by Dr3nz4r** [LorenzoPapi/FreezeTag#1]
Readme states:

> A crewmate can unfreeze a frozen crewmate by standing near him for about 2-3 seconds.

Though the code doesn't seem to care how long you stay beside a frozen crewmate to set back the color to green. I haven't tried this but the code reads like once a crewmate touches a frozen crewmate and runs off, after 2.5s the frozen crewmate will have it's color set back to green but remain frozen.

**Comment by LorenzoPapi** [comment]
https://github.com/LorenzoPapi/FreezeTag/blob/master/FreezeTag/FreezeTagEventListener.cs#L110-L111
In this lines I await the Unfreeze Task and then remove the frozen crewmate from the "frozens" dictionary. I tested it and it works

**Comment by Dr3nz4r** [comment]
Nice, haven't had 4 clients to open a lobby and that looked problematic. I'll close this one. Thanks for clarifying
