### ISSUE TITLE
Custom server breaks public matchmaker

### ISSUE THREAD

**Issue by josiahcbloomer** [LorenzoPapi/FreezeTag#2]
The custom server implementation makes it so every time you try to join a game in the public matchmaker the remote sends a disconnect request. Joining directly by room code works fine.

**Comment by LorenzoPapi** [comment]
I need more information, because this issue doesn't happen to me;
Does a non-modified impostor server work (without my plugin)?
If it doesn't, then it's a problem out of this project
If it does, I'll try to reproduce this issue when I'll be able to

**Comment by LorenzoPapi** [comment]
Closing for missing information.
