### ISSUE TITLE
Invocation of Event PlayerChatEvent threw an exception

### ISSUE THREAD

**Issue by ghost** [LorenzoPapi/FreezeTag#4]
Hello,
My problem is that I get this Error Message whenever I type something in the Chat
![Error](https://user-images.githubusercontent.com/60573119/104822279-ae943880-5841-11eb-94fa-dcedbac20f6d.PNG)

**Comment by LorenzoPapi** [comment]
It's not caused by my plugin, this is FreezeTag plugin, that's Hide and Seek

**Comment by ghost** [comment]
Ah yes, switched the name, thank you
