### ISSUE TITLE
can you help me!?

### ISSUE THREAD

**Issue by mkway1004** [LorenzoPapi/FreezeTag#5]
When I start Imposter server.exe , I find this error
![error](https://user-images.githubusercontent.com/79350957/108585266-de77b400-738a-11eb-8726-88fadb1de832.PNG)

**Comment by LorenzoPapi** [comment]
You have to use custom impostor version, it's in the releases page

**Comment by mkway1004** [comment]
sorry T_T .  I can't find cutom impostor version...

Can you give me link!?

**Comment by mkway1004** [comment]
oh i find!! Thank you!
